project:
  type: website

website:
  title: "Andrew Brown"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: Projects.qmd
        text: Projects

format:
  html:
    theme: spacelab
    css: styles.css
    toc: true

editor: visual

execute: 
  freeze: auto

